services:
  auth-service:
    container_name: auth-service
    environment:
      - SERVICE_CONFIG_APP_NAME=SnackLog
      - SERVICE_CONFIG_ROOT_URL=localhost
      - SERVICE_CONFIG_SERVICE_NAME=auth-service
      - GIN_MODE=debug
    build: .
    ports:
      - 8080:8080
