services:
  auth-service:
    container_name: auth-service
    environment:
      - SERVICE_CONFIG_APP_NAME=SnackLog
      - SERVICE_CONFIG_API_ROOT_URL=localhost
      - SERVICE_CONFIG_SERVICE_NAME=auth-service
      - GIN_MODE=debug
    build: .
    ports:
      - 8080:8080

  # Prostgres Database Service
  auth-service-db:
    image: postgres:18
    container_name: auth-db
    # The credentials below are initial credentials for testing only
    # DO NOT USE IN PRODUCTION!
    environment:
      - POSTGRES_USER=auth_service
      - POSTGRES_PASSWORD=238121a0-3c9b-4d9a-bac1-4badeb3682ee
      - POSTGRES_DB=auth_service
    ports:
      - 5432:5432
    volumes:
      - ./data/pg/:/var/lib/postgresql/
